# Generated by Django 2.2.5 on 2021-11-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.IntegerField(verbose_name='قیمت دلار')),
                ('euro', models.IntegerField(verbose_name='قیمت یورو')),
                ('ratio', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='نسبت دلار به یورو')),
                ('time', models.DateTimeField(verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'قیمت لحظه ای',
                'verbose_name_plural': 'قیمت لحظه ای',
            },
        ),
    ]
