# Generated by Django 2.2.5 on 2021-11-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_auto_20211106_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentprice',
            name='amount',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='currentprice',
            name='name',
            field=models.CharField(max_length=20, verbose_name='نام'),
        ),
    ]
